version: '3.11'


services:
  bot:
    build: .
    #image shokhmee/exam_p18_shohjahon
    restart: always
    container_name: ppt_maker
    environment:
      BOT_TOKEN: 8026550980:AAFGI8zEE5ih0jcf44xmZlYrhzNV9k_l8ec
      DB_NAME: postgres
      DB_PASSWORD: 1
      DB_HOST: pg
      DB_USER: postgres
      DB_PORT: 5432
    depends_on:
      - pg
    command: python3 main.py


  pg:
    image: postgres:alpine
    restart: always
    container_name: contine_ppt_maker
    environment:
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: